# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      #- image: circleci/node:7.10
      - image: docker:17.12.1-ce-git
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: pwd; ls,hostnamectl, uname -or
     
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install node
          command: apt-get -y install node
      - run:
          name: Install node
          command: apt-get -y install npm
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm run wp
      
      - setup_remote_docker
     
      #- run:
      #    name: Install Docker client
      #    command: |
      #      set -x
      #      VER="17.12.1-ce"
      #      curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
      #      tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #      mv /tmp/docker/* /usr/bin
            
      #- run:
      #   name: Build Docker image
      #    command: |
      #      TAG=0.1.$CIRCLE_BUILD_NUM
      #      docker build -t raziaa/todo:$CIRCLE_SHA1 .
         
      - run:
          name: Push to DockerHub
          command: |
            docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD
            docker push raziaa/todo:$CIRCLE_SHA1